version: '3.5'
services:

  postgres-external-source:
    image: postgres:11.6
    environment:
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: dratuti
      POSTGRES_DB: external_data
    volumes:
      - postgres_external_source_volume:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - 54320:5432

  mongo-external-source:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: dratuti
    volumes:
      - mongo_external_source_volume:/data
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: dratuti
      ME_CONFIG_MONGODB_SERVER: mongo-external-source

volumes:
  postgres_external_source_volume:
  mongo_external_source_volume:

networks:
  default:
    external: true
    name: cluster_cluster-network


