version: '3.5'
services:

  master:
    image: spark-node:latest
    env_file:
      - env/master.env
    volumes:
      - master-volume:/spark
      - data-volume:/data
      - jars-volume:/jars
    ports:
      - 7077:7077
      - 8080:8080
      - 4040:4040
      - 9870:9870
      - 9866:9866
      - 54310:54310
    networks:
      - cluster-network

  worker-1:
    image: spark-node:latest
    depends_on:
      - master
    env_file:
      - env/worker.env
    volumes:
      - worker-1-volume:/spark
      - data-volume:/data
      - jars-volume:/jars
    ports:
    - 8081:8081
    - 9867:9866
    networks:
      - cluster-network

  worker-2:
    image: spark-node:latest
    depends_on:
      - master
    env_file:
      - env/worker.env
    volumes:
      - worker-2-volume:/spark
      - data-volume:/data
      - jars-volume:/jars
    ports:
      - 8082:8081
      - 9868:9866
    networks:
      - cluster-network

  client:
    image: spark-client:latest
    depends_on:
      - master
    env_file:
      - env/client.env
    volumes:
      - client-volume:/spark
      - data-volume:/data
      - jars-volume:/jars
    networks:
      - cluster-network
    stdin_open: true
    tty: true

networks:
  cluster-network:

volumes:
  master-volume:
  worker-1-volume:
  worker-2-volume:
  client-volume:
  data-volume:
  jars-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './jars'


